# Generated by Django 6.0.3 on 2026-04-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='idx_staff_sreq_hotel_status',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='idx_staff_sreq_status',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='idx_staff_sreq_priority',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
