# Generated by Django 6.0.3 on 2026-03-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách sạn')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('city', models.CharField(default='Hồ Chí Minh', max_length=100, verbose_name='Thành phố')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(verbose_name='Kinh độ')),
                ('stars', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=3, verbose_name='Số sao')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá / đêm (VNĐ)')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Ảnh chính')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khách sạn',
                'verbose_name_plural': 'Khách sạn',
                'ordering': ['-stars', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục khách sạn',
                'verbose_name_plural': 'Danh mục khách sạn',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('wifi', '📶 WiFi'), ('pool', '🏊 Hồ bơi'), ('gym', '🏋️ Gym'), ('spa', '💆 Spa'), ('restaurant', '🍽️ Nhà hàng'), ('parking', '🚗 Bãi xe'), ('bar', '🍸 Bar'), ('beach', '🏖️ Bãi biển'), ('airport', '✈️ Đưa đón sân bay'), ('laundry', '👕 Giặt ủi'), ('ac', '❄️ Điều hòa'), ('breakfast', '🍳 Bữa sáng')], max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Tiện nghi',
                'verbose_name_plural': 'Tiện nghi',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotelcategory', verbose_name='Danh mục'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Ảnh khách sạn',
                'verbose_name_plural': 'Ảnh khách sạn',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá / đêm')),
                ('capacity', models.IntegerField(default=2, verbose_name='Sức chứa (người)')),
                ('total_rooms', models.IntegerField(default=10, verbose_name='Tổng số phòng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='Khách sạn')),
            ],
            options={
                'verbose_name': 'Loại phòng',
                'verbose_name_plural': 'Loại phòng',
            },
        ),
    ]
