# Generated by Django 6.0.3 on 2026-03-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tiện ích')),
                ('category', models.CharField(choices=[('bedroom', '🛏 Phòng ngủ'), ('bathroom', '🚿 Phòng tắm'), ('entertainment', '📺 Giải trí'), ('kitchen', '🍳 Bếp & Ăn uống'), ('climate', '❄️ Nhiệt độ'), ('accessibility', '♿ Tiếp cận'), ('other', '📦 Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('icon_url', models.CharField(blank=True, max_length=500, verbose_name='URL icon')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Tiện ích',
                'verbose_name_plural': 'Tiện ích',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách sạn')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('city', models.CharField(default='Hồ Chí Minh', max_length=100, verbose_name='Thành phố')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Ví dụ: 10.77386000', max_digits=10, verbose_name='Vĩ độ (latitude)')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Ví dụ: 106.70454900', max_digits=11, verbose_name='Kinh độ (longitude)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('star_rating', models.SmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=3, verbose_name='Số sao')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, verbose_name='URL ảnh đại diện')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Ảnh đại diện (upload)')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Website')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='Giờ nhận phòng')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='Giờ trả phòng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khách sạn',
                'verbose_name_plural': 'Khách sạn',
                'ordering': ['-star_rating', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_hotel_location'), models.Index(fields=['is_active'], name='idx_hotel_active'), models.Index(fields=['city'], name='idx_hotel_city')],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Ảnh khách sạn',
                'verbose_name_plural': 'Ảnh khách sạn',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.amenity', verbose_name='Tiện ích')),
            ],
            options={
                'verbose_name': 'Tiện ích phòng',
                'verbose_name_plural': 'Tiện ích phòng',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại phòng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('max_occupancy', models.SmallIntegerField(default=2, verbose_name='Sức chứa tối đa (người)')),
                ('bed_type', models.CharField(blank=True, choices=[('single', 'Single (1 giường đơn)'), ('double', 'Double (1 giường đôi)'), ('twin', 'Twin (2 giường đơn)'), ('queen', 'Queen'), ('king', 'King'), ('bunk', 'Bunk (2 tầng)'), ('other', 'Khác')], max_length=50, verbose_name='Loại giường')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diện tích (m²)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá / đêm (VNĐ)')),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, verbose_name='URL ảnh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Ảnh (upload)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', through='hotels.RoomAmenity', to='hotels.amenity', verbose_name='Tiện ích')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='Khách sạn')),
            ],
            options={
                'verbose_name': 'Loại phòng',
                'verbose_name_plural': 'Loại phòng',
                'ordering': ['hotel', 'price_per_night'],
            },
        ),
        migrations.AddField(
            model_name='roomamenity',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype', verbose_name='Loại phòng'),
        ),
        migrations.AlterUniqueTogether(
            name='roomamenity',
            unique_together={('room_type', 'amenity')},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Số phòng')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Tầng')),
                ('status', models.CharField(choices=[('available', '✅ Còn trống'), ('occupied', '🔴 Đang có khách'), ('maintenance', '🔧 Đang bảo trì')], default='available', max_length=15, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Khách sạn')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='hotels.roomtype', verbose_name='Loại phòng')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'ordering': ['hotel', 'floor', 'room_number'],
                'indexes': [models.Index(fields=['status'], name='idx_room_status'), models.Index(fields=['hotel'], name='idx_room_hotel')],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
    ]
