# Generated by Django 6.0.3 on 2026-04-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'Ảnh loại phòng',
                'verbose_name_plural': 'Ảnh loại phòng',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='HotelCategory',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Ảnh đại diện'),
        ),
    ]
