# Generated by Django 4.2.29 on 2026-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="amenities",
            field=models.ManyToManyField(
                blank=True,
                related_name="hotels",
                to="hotels.amenity",
                verbose_name="Tiện ích khách sạn",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="price_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bỏ trống sẽ tự tính xấp xỉ = giá/đêm ÷ 24 khi đặt theo giờ.",
                max_digits=12,
                null=True,
                verbose_name="Giá / giờ (VNĐ)",
            ),
        ),
    ]
