# Generated by Django 6.0.3 on 2026-04-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roomtypeimage_delete_hotelcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên dịch vụ')),
                ('category', models.CharField(choices=[('food', '🍽 Ăn uống & Room Service'), ('spa', '💆 Spa & Thư giãn'), ('laundry', '👕 Giặt ủi'), ('housekeeping', '🧹 Dọn phòng'), ('transport', '🚗 Xe đưa đón'), ('concierge', '🔔 Concierge'), ('tech', '📱 Kỹ thuật & IT'), ('other', '✨ Khác')], default='other', max_length=20, verbose_name='Danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(default='✨', help_text='Emoji đại diện, vd: 🍔', max_length=10, verbose_name='Emoji icon')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Để trống nếu miễn phí', max_digits=12, null=True, verbose_name='Giá (VNĐ)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('requires_note', models.BooleanField(default=False, help_text='Bật nếu dịch vụ cần thêm chi tiết từ khách', verbose_name='Yêu cầu ghi chú')),
                ('eta_minutes', models.SmallIntegerField(blank=True, null=True, verbose_name='Thời gian ước tính (phút)')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel', verbose_name='Khách sạn')),
            ],
            options={
                'verbose_name': 'Dịch vụ khách sạn',
                'verbose_name_plural': 'Dịch vụ khách sạn',
                'ordering': ['hotel', 'category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Tên khách (nếu chưa đăng nhập)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú / yêu cầu thêm')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='Số lượng')),
                ('status', models.CharField(choices=[('pending', '⏳ Chờ xử lý'), ('accepted', '✅ Đã tiếp nhận'), ('processing', '🔄 Đang thực hiện'), ('done', '✔️ Hoàn thành'), ('cancelled', '❌ Đã huỷ')], default='pending', max_length=15, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('normal', 'Thường'), ('urgent', '🚨 Khẩn')], default='normal', max_length=10, verbose_name='Ưu tiên')),
                ('staff_note', models.TextField(blank=True, verbose_name='Ghi chú nhân viên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Khách')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='hotels.room', verbose_name='Phòng')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hotels.hotelservice', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Yêu cầu dịch vụ',
                'verbose_name_plural': 'Yêu cầu dịch vụ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_sreq_status'), models.Index(fields=['room'], name='idx_sreq_room'), models.Index(fields=['created_at'], name='idx_sreq_created')],
            },
        ),
    ]
