# Generated by Django 6.0.3 on 2026-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_short_description_homepageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='short_description',
            field=models.CharField(blank=True, help_text='Hiển thị trong card danh sách và hero. Tối đa 300 ký tự.', max_length=300, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả dài (chi tiết)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả dài (chi tiết)'),
        ),
    ]
