# Generated by Django 6.0.1 on 2026-02-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0002_customer_discountcode_alter_hotel_options_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotels',
        ),
    ]
