# Generated by Django 6.0.1 on 2026-02-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_api', '0003_alter_hotel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
    ]
