# Generated by Django 4.2.29 on 2026-03-29 13:43

import inspect

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


_CHECKCONSTRAINT_EXPR_KWARG = (
    "check"
    if "check" in inspect.signature(models.CheckConstraint).parameters
    else "condition"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField(verbose_name="Ngày nhận phòng")),
                ("check_out", models.DateField(verbose_name="Ngày trả phòng")),
                (
                    "num_guests",
                    models.SmallIntegerField(default=1, verbose_name="Số khách"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Tổng tiền (VNĐ)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Chờ xác nhận"),
                            ("confirmed", "✅ Đã xác nhận"),
                            ("checked_in", "🏨 Đang ở"),
                            ("checked_out", "🚪 Đã trả phòng"),
                            ("cancelled", "❌ Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Yêu cầu đặc biệt")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm hủy"
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="Lý do hủy"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="hotels.room",
                        verbose_name="Phòng",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đặt phòng",
                "verbose_name_plural": "Đặt phòng",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ],
                        verbose_name="Điểm đánh giá (1-5)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Nhận xét")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Hiển thị công khai"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="bookings.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hotels.hotel",
                        verbose_name="Khách sạn",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["hotel"], name="idx_review_hotel"),
                    models.Index(fields=["rating"], name="idx_review_rating"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số tiền"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "💵 Tiền mặt"),
                            ("credit_card", "💳 Thẻ tín dụng"),
                            ("debit_card", "💳 Thẻ ghi nợ"),
                            ("bank_transfer", "🏦 Chuyển khoản"),
                            ("e_wallet", "📱 Ví điện tử"),
                            ("momo", "🟣 MoMo"),
                            ("vnpay", "🔵 VNPay"),
                            ("zalopay", "🔷 ZaloPay"),
                        ],
                        max_length=20,
                        verbose_name="Phương thức",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ Chờ thanh toán"),
                            ("paid", "✅ Đã thanh toán"),
                            ("failed", "❌ Thất bại"),
                            ("refunded", "🔄 Đã hoàn tiền"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mã giao dịch"
                    ),
                ),
                (
                    "gateway_response",
                    models.TextField(
                        blank=True, verbose_name="Phản hồi cổng thanh toán (JSON)"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm thanh toán"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời điểm hoàn tiền"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Số tiền hoàn",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú kế toán")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="bookings.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thanh toán",
                "verbose_name_plural": "Thanh toán",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["booking"], name="idx_payment_booking"),
                    models.Index(fields=["status"], name="idx_payment_status"),
                    models.Index(
                        fields=["transaction_code"], name="idx_payment_transaction"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user"], name="idx_booking_customer"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["room"], name="idx_booking_room"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in", "check_out"], name="idx_booking_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="idx_booking_status"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                **{
                    _CHECKCONSTRAINT_EXPR_KWARG: models.Q(
                        ("check_out__gt", models.F("check_in"))
                    ),
                    "name": "chk_checkout_after_checkin",
                }
            ),
        ),
    ]
