# Generated by Django 6.0.3 on 2026-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requires_prepayment',
            field=models.BooleanField(default=False, help_text='Tự động True khi đặt từ 2 phòng trở lên trong cùng 1 lần đặt', verbose_name='Bắt buộc thanh toán trước'),
        ),
    ]
