# Generated by Codex on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=64, verbose_name="Mã tham chiếu"),
        ),
        migrations.AddField(
            model_name="payment",
            name="qr_payload",
            field=models.TextField(blank=True, verbose_name="Nội dung QR (payload/link)"),
        ),
        migrations.AddField(
            model_name="payment",
            name="qr_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="URL ảnh QR"),
        ),
    ]

