# Generated by Django 4.2.29 on 2026-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_payment_qr_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="chk_checkout_after_checkin",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[("daily", "🗓 Theo ngày"), ("hourly", "🕐 Theo giờ")],
                default="daily",
                max_length=10,
                verbose_name="Loại đặt phòng",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_in_dt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Giờ nhận phòng"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_dt",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Giờ trả phòng"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày nhận phòng"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày trả phòng"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("booking_type", "daily"),
                            ("check_in__isnull", False),
                            ("check_out__gt", models.F("check_in")),
                            ("check_out__isnull", False),
                        ),
                        models.Q(
                            ("booking_type", "hourly"),
                            ("check_in_dt__isnull", False),
                            ("check_out_dt__gt", models.F("check_in_dt")),
                            ("check_out_dt__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="chk_checkout_after_checkin",
            ),
        ),
    ]
