# Generated by Django 5.0.4 on 2026-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_hourly_amenityusage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="chk_checkout_after_checkin",
        ),
        migrations.AlterField(
            model_name="booking",
            name="requires_prepayment",
            field=models.BooleanField(
                default=False, verbose_name="Bắt buộc thanh toán trước"
            ),
        ),
    ]
