# Generated by Django 4.2.29 on 2026-04-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotel_amenities_roomtype_price_per_hour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0003_remove_booking_chk_checkout_after_checkin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenityUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Số lượng/lượt"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "used_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời điểm sử dụng",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usages",
                        to="hotels.amenity",
                        verbose_name="Tiện ích",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_usages",
                        to="bookings.booking",
                        verbose_name="Đặt phòng",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenity_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sử dụng tiện ích",
                "verbose_name_plural": "Sử dụng tiện ích",
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(fields=["booking"], name="idx_amenity_usage_booking"),
                    models.Index(fields=["user"], name="idx_amenity_usage_user"),
                    models.Index(fields=["amenity"], name="idx_amenity_usage_amenity"),
                ],
            },
        ),
    ]
